server:
  port: 9091

spring:
  datasource:
    platform: MYSQL
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/dim_light?serverTimezone=GMT%2B8&useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: 123456
    #表明使用的数据库平台是 sqlite
    #platform: sqlite
    #driver-class-name: org.sqlite.JDBC
    #url: jdbc:sqlite:DimLight.db
    #username: admin
    #password: 123456
  jpa:
    hibernate:
      # create/update 该选项会导致mysql很多表的创建报错
      ddl-auto: update
      naming:
        # 当没有使用@Table和@Column注解时，implicit-strategy配置项才会被使用，当对象模型中已经指定时，implicit-strategy并不会起作用
        # physical-strategy一定会被应用
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    # 数据库方言配置
    # database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database-platform: org.hibernate.dialect.MySQL8Dialect
    # 打印sql语句，方便调试
    show-sql: false
  servlet:
    multipart:
      enabled: true #默认支持文件上传.
      file-size-threshold: 0 #支持文件写入磁盘.
      # location:  # 上传文件的临时目录
      max-file-size: 10485760 # 最大支持文件大小 10M
      max-request-size: 10485760 # 最大支持请求大小 10M
  # http://www.quartz-scheduler.org/documentation/quartz-2.1.7/configuration/index.html
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
      # https://github.com/quartz-scheduler/quartz/blob/master/quartz-core/src/main/resources/org/quartz/impl/jdbcjobstore/tables_mysql_innodb.sql
      schema: classpath:quartz_innodb.sql
    auto-startup: true
    properties:
      org:
        quartz:
          scheduler:
            instanceName: dimlightScheduler
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            # isClustered: false
            # clusterCheckinInterval: 10000
            # useProperties: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true


# 某些重要操作所需的密钥
url.token: lxhjoi2974o0snxgt