server:
  port: 9091

spring:
  datasource:
    #表明使用的数据库平台是 sqlite
    platform: sqlite
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:DimLight.db
    username: admin
    password: 123456
  jpa:
    hibernate:
      # 注意这个 auto 的取值
      # https://blog.csdn.net/qq_36666651/article/details/80719259
      ddl-auto: update
    # 数据库方言配置
    database-platform: com.highestpeak.dimlight.config.SQLiteDialect
    show-sql: true
  servlet:
    multipart:
      enabled: true #默认支持文件上传.
      file-size-threshold: 0 #支持文件写入磁盘.
      # location:  # 上传文件的临时目录
      max-file-size: 10485760 # 最大支持文件大小 10M
      max-request-size: 10485760 # 最大支持请求大小 10M